version: "5.1"

services:
  backend:
    build: .
    container_name: node-backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/quiez-app
    command: npm run dev
    networks:
      - anket-app-network

  mongo:
    image: mongo:6.0
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - anket-app-network

  seed_data:
    build: .
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - anket-app-network
    command: npm run seed
    restart: "no"

volumes:
  mongo-data:

networks:
  anket-app-network: # <-- The network must be defined here
    driver: bridge
